#!/bin/bash

################################################################################
# Superset DHIS2 Deployment Script
#
# This script handles complete setup and deployment of Superset with DHIS2
# integration including:
# - Environment setup
# - Database initialization
# - DHIS2 caching configuration
# - Embedded dashboard setup
# - Service management
#
# Usage:
#   ./deploy.sh install    - First-time installation
#   ./deploy.sh start      - Start all services
#   ./deploy.sh stop       - Stop all services
#   ./deploy.sh restart    - Restart all services
#   ./deploy.sh status     - Check service status
#   ./deploy.sh upgrade    - Upgrade database and apply migrations
#   ./deploy.sh clear-cache - Clear DHIS2 cache
################################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Deployment configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${SCRIPT_DIR}/venv"
LOG_DIR="${SCRIPT_DIR}/logs"
DATA_DIR="${SCRIPT_DIR}/data"
CONFIG_FILE="${SCRIPT_DIR}/superset_config.py"
EMBEDDED_INIT="${SCRIPT_DIR}/init_embedded.py"

# Print colored message
print_msg() {
    local color=$1
    shift
    echo -e "${color}[$(date +'%Y-%m-%d %H:%M:%S')] $@${NC}"
}

print_info() { print_msg "$BLUE" "ℹ️  $@"; }
print_success() { print_msg "$GREEN" "✅ $@"; }
print_warning() { print_msg "$YELLOW" "⚠️  $@"; }
print_error() { print_msg "$RED" "❌ $@"; }

# Check if running as root
check_not_root() {
    if [ "$EUID" -eq 0 ]; then
        print_error "Please do not run this script as root"
        exit 1
    fi
}

# Check prerequisites
check_prerequisites() {
    print_info "Checking prerequisites..."

    local missing_deps=()

    # Check Python
    if ! command -v python3 &> /dev/null; then
        missing_deps+=("python3")
    fi

    # Check pip
    if ! command -v pip3 &> /dev/null; then
        missing_deps+=("python3-pip")
    fi

    # Check Node.js (for frontend)
    if ! command -v node &> /dev/null; then
        print_warning "Node.js not found - frontend build will be skipped"
    fi

    if [ ${#missing_deps[@]} -gt 0 ]; then
        print_error "Missing dependencies: ${missing_deps[*]}"
        print_info "Install them with: sudo apt-get install ${missing_deps[*]}"
        exit 1
    fi

    print_success "Prerequisites check passed"
}

# Setup Python virtual environment
setup_venv() {
    print_info "Setting up Python virtual environment..."

    if [ ! -d "$VENV_DIR" ]; then
        python3 -m venv "$VENV_DIR"
        print_success "Virtual environment created"
    else
        print_info "Virtual environment already exists"
    fi

    # Activate virtual environment
    source "$VENV_DIR/bin/activate"

    # Upgrade pip
    pip install --upgrade pip

    print_success "Virtual environment ready"
}

# Install Python dependencies
install_dependencies() {
    print_info "Installing Python dependencies..."

    source "$VENV_DIR/bin/activate"

    # Install Superset and dependencies
    pip install apache-superset

    # Install DHIS2-specific dependencies
    pip install psycopg2-binary  # PostgreSQL support
    pip install gevent           # Async support

    print_success "Dependencies installed"
}

# Create directory structure
create_directories() {
    print_info "Creating directory structure..."

    mkdir -p "$LOG_DIR"
    mkdir -p "$DATA_DIR"
    mkdir -p "${SCRIPT_DIR}/static/assets"

    print_success "Directories created"
}

# Generate superset_config.py
generate_config() {
    print_info "Generating Superset configuration..."

    if [ -f "$CONFIG_FILE" ]; then
        print_warning "Configuration file already exists, backing up..."
        cp "$CONFIG_FILE" "${CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    fi

    cat > "$CONFIG_FILE" << 'EOF'
# Superset Configuration with DHIS2 Integration
# Auto-generated by deploy.sh

import os
from datetime import timedelta

# Base directory
BASE_DIR = os.path.abspath(os.path.dirname(__file__))

# ---------------------------------------------------------
# Superset specific config
# ---------------------------------------------------------
ROW_LIMIT = 50000
SUPERSET_WEBSERVER_PORT = 8088

# ---------------------------------------------------------
# Base URL Configuration (for embedded dashboards)
# ---------------------------------------------------------
# Set this to your production URL when deploying to a server
# Examples:
#   Development: http://localhost:8088
#   Production:  https://superset.yourdomain.com
SUPERSET_BASE_URL = os.environ.get('SUPERSET_BASE_URL', 'http://localhost:8088')

# Flask App Builder configuration
SECRET_KEY = os.environ.get('SUPERSET_SECRET_KEY', 'CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET')

# Database configuration
SQLALCHEMY_DATABASE_URI = os.environ.get(
    'DATABASE_URL',
    f'sqlite:///{os.path.join(BASE_DIR, "data", "superset.db")}'
)

# Prevent tracking modifications
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Data and upload folders
DATA_DIR = os.path.join(BASE_DIR, 'data')
UPLOAD_FOLDER = os.path.join(DATA_DIR, 'uploads')

# Logging
LOG_LEVEL = 'INFO'
LOG_FORMAT = '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
LOG_FILE = os.path.join(BASE_DIR, 'logs', 'superset.log')

# Enable CORS
ENABLE_CORS = True
CORS_OPTIONS = {
    'supports_credentials': True,
    'allow_headers': ['*'],
    'resources': ['*'],
    'origins': ['*']
}

# ---------------------------------------------------------
# DHIS2 Caching Configuration
# ---------------------------------------------------------

# DHIS2 cache refresh interval (seconds) - default 6 hours
DHIS2_CACHE_REFRESH_INTERVAL = 21600

# Cache TTLs (seconds)
DHIS2_CACHE_TTL = {
    'geojson': 21600,       # 6 hours - geo boundaries rarely change
    'org_hierarchy': 3600,  # 1 hour - hierarchy changes rarely
    'org_levels': 7200,     # 2 hours - levels never change
    'analytics': 1800,      # 30 minutes - data updates periodically
    'filter_options': 3600, # 1 hour - filter options change rarely
    'name_to_uid': 3600,    # 1 hour - org unit names stable
}

# Cache size limit (MB)
DHIS2_CACHE_MAX_SIZE_MB = 500

# ---------------------------------------------------------
# Feature Flags
# ---------------------------------------------------------
FEATURE_FLAGS = {
    'DASHBOARD_NATIVE_FILTERS': True,
    'DASHBOARD_CROSS_FILTERS': True,
    'DASHBOARD_NATIVE_FILTERS_SET': True,
    'ENABLE_TEMPLATE_PROCESSING': True,
    'EMBEDDED_SUPERSET': True,
    'DYNAMIC_PLUGINS': True,
}

# ---------------------------------------------------------
# Embedded Configuration
# ---------------------------------------------------------
GUEST_ROLE_NAME = 'Public'
GUEST_TOKEN_JWT_SECRET = os.environ.get('GUEST_TOKEN_JWT_SECRET', 'CHANGE_ME_TO_A_COMPLEX_RANDOM_SECRET')
GUEST_TOKEN_JWT_ALGO = 'HS256'
GUEST_TOKEN_HEADER_NAME = 'X-GuestToken'
GUEST_TOKEN_JWT_EXP_SECONDS = 300  # 5 minutes

# Embedded dashboard domains
EMBEDDED_ALLOWED_DOMAINS = [
    'localhost',
    '127.0.0.1',
    # Add your production domains here
]

# ---------------------------------------------------------
# Security
# ---------------------------------------------------------
WTF_CSRF_ENABLED = True
WTF_CSRF_EXEMPT_LIST = ['superset.views.core.log']
WTF_CSRF_TIME_LIMIT = None

# ---------------------------------------------------------
# Async Queries
# ---------------------------------------------------------
GLOBAL_ASYNC_QUERIES_TRANSPORT = 'polling'
GLOBAL_ASYNC_QUERIES_POLLING_DELAY = 500

# ---------------------------------------------------------
# Custom Initialization
# ---------------------------------------------------------
def FLASK_APP_MUTATOR(app):
    """Custom app initialization - runs after Superset setup."""
    # This is called by Superset initialization
    # Additional custom setup can be added here
    pass

EOF

    print_success "Configuration file generated: $CONFIG_FILE"
    print_warning "IMPORTANT: Edit $CONFIG_FILE and set proper SECRET_KEY and GUEST_TOKEN_JWT_SECRET"
}

# Generate init_embedded.py
generate_embedded_init() {
    print_info "Generating embedded dashboard initialization script..."

    cat > "$EMBEDDED_INIT" << 'EOF'
#!/usr/bin/env python3
"""
Initialize embedded dashboards for guest access.

This script:
1. Creates a 'Public' role with read-only access
2. Creates a 'guest' user with Public role
3. Enables embedded access for specified dashboards
4. Configures permissions for guest access

Usage:
    python init_embedded.py [dashboard_id1] [dashboard_id2] ...

    If no dashboard IDs provided, enables all dashboards for embedding.
"""

import sys
import logging
from superset import app, db, security_manager
from superset.models.dashboard import Dashboard
from superset.models.slice import Slice
from flask_appbuilder.security.sqla.models import Role, User

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def create_public_role():
    """Create Public role with read-only permissions."""
    logger.info("Creating/updating Public role...")

    # Get or create Public role
    public_role = security_manager.find_role('Public')

    if not public_role:
        public_role = security_manager.add_role('Public')
        logger.info("Created new Public role")

    # Define permissions for Public role
    permissions = [
        # Dashboard permissions
        ('can_read', 'Dashboard'),
        ('can_dashboard', 'Superset'),

        # Chart permissions
        ('can_read', 'Chart'),
        ('can_explore_json', 'Superset'),

        # Dataset permissions
        ('can_read', 'Dataset'),
        ('can_get', 'Datasource'),

        # Database permissions
        ('can_read', 'Database'),

        # Query permissions
        ('can_read', 'Query'),

        # Embedded permissions
        ('can_read', 'EmbeddedDashboard'),
    ]

    # Add permissions to role
    for permission_name, view_name in permissions:
        perm_view = security_manager.find_permission_view_menu(permission_name, view_name)
        if perm_view and perm_view not in public_role.permissions:
            public_role.permissions.append(perm_view)

    db.session.commit()
    logger.info("Public role configured with permissions")

    return public_role


def create_guest_user(public_role):
    """Create guest user with Public role."""
    logger.info("Creating/updating guest user...")

    # Check if guest user exists
    guest_user = security_manager.find_user('guest')

    if not guest_user:
        guest_user = security_manager.add_user(
            username='guest',
            first_name='Guest',
            last_name='User',
            email='guest@localhost',
            role=public_role,
            password='guest'  # Will be changed to a secure password
        )
        logger.info("Created new guest user")
    else:
        # Update role if needed
        if public_role not in guest_user.roles:
            guest_user.roles.append(public_role)
            db.session.commit()
            logger.info("Updated guest user role")

    return guest_user


def enable_embedded_dashboards(dashboard_ids=None):
    """Enable embedded access for dashboards.

    Args:
        dashboard_ids: List of dashboard IDs to enable. If None, enables all dashboards.
    """
    logger.info("Enabling embedded access for dashboards...")

    if dashboard_ids:
        dashboards = Dashboard.query.filter(Dashboard.id.in_(dashboard_ids)).all()
    else:
        dashboards = Dashboard.query.all()

    if not dashboards:
        logger.warning("No dashboards found")
        return

    enabled_count = 0
    for dashboard in dashboards:
        if not dashboard.embedded:
            dashboard.embedded = []

        # Enable embedded access
        if 'allow_domain_list' not in dashboard.embedded:
            dashboard.embedded.append({
                'allow_domain_list': ['*'],  # Allow all domains (configure in superset_config.py)
            })
            enabled_count += 1
            logger.info(f"Enabled embedding for dashboard: {dashboard.dashboard_title} (ID: {dashboard.id})")

    db.session.commit()
    logger.info(f"Enabled embedding for {enabled_count} dashboards")


def grant_dashboard_permissions(public_role):
    """Grant Public role access to all dashboards and charts."""
    logger.info("Granting dashboard and chart permissions to Public role...")

    # Get all dashboards
    dashboards = Dashboard.query.all()

    for dashboard in dashboards:
        # Create permission for this dashboard
        perm_view = security_manager.find_permission_view_menu(
            'can_read',
            f'[Dashboard].(id:{dashboard.id})'
        )

        if perm_view and perm_view not in public_role.permissions:
            public_role.permissions.append(perm_view)

    # Get all charts
    charts = Slice.query.all()

    for chart in charts:
        # Create permission for this chart
        perm_view = security_manager.find_permission_view_menu(
            'can_read',
            f'[Chart].(id:{chart.id})'
        )

        if perm_view and perm_view not in public_role.permissions:
            public_role.permissions.append(perm_view)

    db.session.commit()
    logger.info(f"Granted permissions for {len(dashboards)} dashboards and {len(charts)} charts")


def main():
    """Main initialization function."""
    logger.info("=" * 80)
    logger.info("Starting embedded dashboard initialization")
    logger.info("=" * 80)

    with app.app_context():
        # Get dashboard IDs from command line
        dashboard_ids = None
        if len(sys.argv) > 1:
            try:
                dashboard_ids = [int(id_str) for id_str in sys.argv[1:]]
                logger.info(f"Will enable embedding for specific dashboards: {dashboard_ids}")
            except ValueError:
                logger.error("Invalid dashboard IDs provided. Use integers only.")
                sys.exit(1)

        # Step 1: Create Public role
        public_role = create_public_role()

        # Step 2: Create guest user
        guest_user = create_guest_user(public_role)

        # Step 3: Enable embedded access for dashboards
        enable_embedded_dashboards(dashboard_ids)

        # Step 4: Grant permissions
        grant_dashboard_permissions(public_role)

        logger.info("=" * 80)
        logger.info("Embedded dashboard initialization complete!")
        logger.info("=" * 80)
        logger.info(f"Guest user: guest")
        logger.info(f"Public role: Public")
        logger.info("Next steps:")
        logger.info("1. Update GUEST_TOKEN_JWT_SECRET in superset_config.py")
        logger.info("2. Configure EMBEDDED_ALLOWED_DOMAINS in superset_config.py")
        logger.info("3. Restart Superset")


if __name__ == '__main__':
    main()
EOF

    chmod +x "$EMBEDDED_INIT"
    print_success "Embedded initialization script generated: $EMBEDDED_INIT"
}

# Initialize Superset database
init_database() {
    print_info "Initializing Superset database..."

    source "$VENV_DIR/bin/activate"

    # Set environment variables
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"
    export FLASK_APP=superset

    # Initialize database
    superset db upgrade

    # Create default roles and permissions
    superset init

    print_success "Database initialized"
}

# Create admin user
create_admin() {
    print_info "Creating admin user..."

    source "$VENV_DIR/bin/activate"
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"
    export FLASK_APP=superset

    # Check if admin exists
    if superset fab list-users | grep -q "admin"; then
        print_info "Admin user already exists"
    else
        # Create admin user interactively
        print_info "Please provide admin user details:"
        superset fab create-admin
        print_success "Admin user created"
    fi
}

# Initialize embedded dashboards
init_embedded() {
    print_info "Initializing embedded dashboards..."

    source "$VENV_DIR/bin/activate"
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"

    python "$EMBEDDED_INIT"

    print_success "Embedded dashboards initialized"
}

# Start Superset services
start_services() {
    print_info "Starting Superset services..."

    source "$VENV_DIR/bin/activate"
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"
    export FLASK_APP=superset

    # Use superset-manager.sh if it exists
    if [ -f "${SCRIPT_DIR}/superset-manager.sh" ]; then
        "${SCRIPT_DIR}/superset-manager.sh" start
    else
        # Fallback to direct superset run
        nohup superset run -h 0.0.0.0 -p 8088 --with-threads > "$LOG_DIR/superset.log" 2>&1 &
        echo $! > "$DATA_DIR/superset.pid"
    fi

    print_success "Superset services started"
    print_info "Access Superset at: http://localhost:8088"
}

# Stop Superset services
stop_services() {
    print_info "Stopping Superset services..."

    # Use superset-manager.sh if it exists
    if [ -f "${SCRIPT_DIR}/superset-manager.sh" ]; then
        "${SCRIPT_DIR}/superset-manager.sh" stop
    else
        # Fallback to PID file
        if [ -f "$DATA_DIR/superset.pid" ]; then
            kill $(cat "$DATA_DIR/superset.pid") 2>/dev/null || true
            rm "$DATA_DIR/superset.pid"
        fi
    fi

    print_success "Superset services stopped"
}

# Restart services
restart_services() {
    stop_services
    sleep 2
    start_services
}

# Check service status
check_status() {
    print_info "Checking Superset status..."

    # Use superset-manager.sh if it exists
    if [ -f "${SCRIPT_DIR}/superset-manager.sh" ]; then
        "${SCRIPT_DIR}/superset-manager.sh" status
    else
        if [ -f "$DATA_DIR/superset.pid" ] && kill -0 $(cat "$DATA_DIR/superset.pid") 2>/dev/null; then
            print_success "Superset is running (PID: $(cat $DATA_DIR/superset.pid))"
        else
            print_warning "Superset is not running"
        fi
    fi
}

# Upgrade database
upgrade_database() {
    print_info "Upgrading database..."

    source "$VENV_DIR/bin/activate"
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"
    export FLASK_APP=superset

    superset db upgrade

    print_success "Database upgraded"
}

# Clear DHIS2 cache
clear_cache() {
    print_info "Clearing DHIS2 cache..."

    source "$VENV_DIR/bin/activate"
    export SUPERSET_CONFIG_PATH="$CONFIG_FILE"

    python << 'PYTHON_SCRIPT'
from superset.utils.dhis2_cache import get_dhis2_cache

cache = get_dhis2_cache()
count = cache.clear()
print(f"Cleared {count} cache entries")

stats = cache.stats()
print(f"Cache stats: {stats}")
PYTHON_SCRIPT

    print_success "DHIS2 cache cleared"
}

# Full installation
full_install() {
    print_info "========================================="
    print_info "Starting full Superset installation"
    print_info "========================================="

    check_not_root
    check_prerequisites
    setup_venv
    install_dependencies
    create_directories
    generate_config
    generate_embedded_init
    init_database
    create_admin

    print_success "========================================="
    print_success "Installation complete!"
    print_success "========================================="
    print_info "Next steps:"
    print_info "1. Edit $CONFIG_FILE and set SECRET_KEY and GUEST_TOKEN_JWT_SECRET"
    print_info "2. Run: ./deploy.sh start"
    print_info "3. (Optional) Run: ./deploy.sh init-embedded"
}

# Show usage
show_usage() {
    cat << EOF
Usage: $0 {command}

Commands:
    install         - Full installation (first time only)
    start           - Start Superset services
    stop            - Stop Superset services
    restart         - Restart Superset services
    status          - Check service status
    upgrade         - Upgrade database schema
    clear-cache     - Clear DHIS2 cache
    init-embedded   - Initialize embedded dashboards
    help            - Show this help message

Examples:
    $0 install              # First-time installation
    $0 start                # Start services
    $0 init-embedded 1 2 3  # Enable embedding for dashboards 1, 2, 3
    $0 clear-cache          # Clear DHIS2 cache

EOF
}

# Main command dispatcher
main() {
    case "${1:-}" in
        install)
            full_install
            ;;
        start)
            start_services
            ;;
        stop)
            stop_services
            ;;
        restart)
            restart_services
            ;;
        status)
            check_status
            ;;
        upgrade)
            upgrade_database
            ;;
        clear-cache)
            clear_cache
            ;;
        init-embedded)
            shift
            init_embedded "$@"
            ;;
        help|--help|-h)
            show_usage
            ;;
        *)
            print_error "Unknown command: ${1:-}"
            show_usage
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
