ATTACH TABLE _ UUID '7c3a1380-6620-4da0-8d78-5e5d37345a5b'
(
    `national` LowCardinality(String),
    `region` LowCardinality(String),
    `district_city` LowCardinality(String),
    `dlg_municipality_city_council` LowCardinality(String),
    `sub_county_town_council_division` LowCardinality(String),
    `health_facility` LowCardinality(String),
    `ward_department` LowCardinality(String),
    `period` LowCardinality(String),
    `ou_level` UInt16,
    `period_variant` LowCardinality(String),
    `mal_malaria_deaths_per_100_000` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_villages_reporting_stock_out_of_act` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_suspected_malaria_cases_tested_within_the_community` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_facilities_with_1_day_stock_out_of_rdt_in_last_month` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_villages_reporting_stock_out_of_malaria_rapid_diagnostic_tests` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_malaria_in_pregnancy_case_fatality_rate` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_pregnant_women_diagnosed_with_malaria` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_facilities_with_1_day_stock_out_of_artesunate_in_last_month` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_testing_rate` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_under_5_malaria_deaths` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_under_5_of_all_malaria_cases` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_ipt2_coverage` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_test_positivity_rate` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_opd_malaria_cases_to_opd_attendance` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_malaria_in_pregancy_deaths_per_100_000` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_facilities_with_1_day_stock_out_of_sp_in_last_month` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_tested_negative_treated` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_confirmed_malaria_cases_treated` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_malaria_case_fatality_rate` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_children_seen_by_vht_and_treated_within_24hrs_for_fever` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_under_5_malaria_cases_diagnosed_by_vht` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_not_tested_treated` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_total_admissions_that_are_due_to_malaria` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_total_all_cause_deaths_that_is_due_to_malaria` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_facilities_with_1_day_stock_out_of_al_in_last_month` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_malaria_annual_parasite_incidence_per_1000` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_pregnant_women_receiving_llins_on_1st_anc_visit` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_confirmed_malaria_cases_treated_within_the_community` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_children_with_fever_and_danger_sign_treated_with_rectal_artesunate` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_routine_llin_coverage_for_5` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_ipt3_coverage` Nullable(Float64) CODEC(ZSTD(3)),
    `mal_proportion_of_under_5_children_receiving_treatment_within_24_hours_of_onset_of_fever` Nullable(Float64) CODEC(ZSTD(3)),
    `_manifest_build_v5` Nullable(Int64)
)
ENGINE = MergeTree
PARTITION BY toUInt16OrZero(substring(replaceRegexpAll(ifNull(period, ''), '[^0-9]', ''), 1, 4))
ORDER BY (period, ou_level, national, region, district_city, dlg_municipality_city_council, sub_county_town_council_division, health_facility, ward_department)
SETTINGS allow_nullable_key = 1, index_granularity = 8192
