/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import reducerIndex from 'spec/helpers/reducerIndex';
import {
  createStore,
  render,
  screen,
  userEvent,
  waitFor,
} from 'spec/helpers/testing-library';
import { extraQueryEditor2, initialState } from 'src/SqlLab/fixtures';
import SqlEditorLeftBar from 'src/SqlLab/components/SqlEditorLeftBar';

let mockSelectedTables: Array<{
  label: string;
  value: string;
  type: string;
}> = [{ label: 'ab_user', value: 'ab_user', type: 'table' }];

jest.mock('src/components/TableSelector', () => ({
  TableSelectorMultiple: ({
    onTableSelectChange,
  }: {
    onTableSelectChange?: (
      value?: unknown[],
      catalog?: string | null,
      schema?: string,
    ) => void;
  }) => (
    <button
      type="button"
      onClick={() =>
        onTableSelectChange?.(
          mockSelectedTables,
          null,
          'main',
        )
      }
    >
      Select table
    </button>
  ),
}));

jest.mock('src/SqlLab/components/TableElement', () => () => (
  <div data-test="mock-table-element" />
));

const mockedDatabase = {
  id: 1,
  database_name: 'main',
  backend: 'mysql',
};

function renderWithQueryEditor(
  queryEditor: typeof extraQueryEditor2,
  tables: typeof initialState.sqlLab.tables = [],
) {
  const store = createStore(
    {
      ...initialState,
      sqlLab: {
        ...initialState.sqlLab,
        queryEditors: [queryEditor],
        tabHistory: [queryEditor.id],
        tables,
      },
    },
    reducerIndex,
  );

  render(
    <SqlEditorLeftBar
      queryEditorId={queryEditor.id}
      database={mockedDatabase}
    />,
    { useRedux: true, store },
  );

  return store;
}

function getCurrentEditorSql(
  store: ReturnType<typeof createStore>,
  queryEditorId: string,
) {
  const {
    sqlLab: { unsavedQueryEditor, queryEditors },
  } = store.getState();
  return unsavedQueryEditor.id === queryEditorId
    ? unsavedQueryEditor.sql
    : queryEditors.find(({ id }) => id === queryEditorId)?.sql;
}

test('generates default SQL when a single table is selected into a blank editor', async () => {
  mockSelectedTables = [{ label: 'ab_user', value: 'ab_user', type: 'table' }];
  const store = renderWithQueryEditor({
    ...extraQueryEditor2,
    dbId: mockedDatabase.id,
    schema: 'main',
  });

  await userEvent.click(screen.getByRole('button', { name: 'Select table' }));

  await waitFor(() =>
    expect(getCurrentEditorSql(store, extraQueryEditor2.id)).toBe(
      'SELECT * FROM main.ab_user',
    ),
  );
});

test('does not overwrite manual SQL when selecting a table', async () => {
  mockSelectedTables = [{ label: 'ab_user', value: 'ab_user', type: 'table' }];
  const store = renderWithQueryEditor({
    ...extraQueryEditor2,
    dbId: mockedDatabase.id,
    schema: 'main',
    sql: 'SELECT 1',
  });

  await userEvent.click(screen.getByRole('button', { name: 'Select table' }));

  await waitFor(() =>
    expect(getCurrentEditorSql(store, extraQueryEditor2.id)).toBe('SELECT 1'),
  );
});

test('replaces placeholder SQL when selecting a table in the active editor', async () => {
  mockSelectedTables = [{ label: 'ab_user', value: 'ab_user', type: 'table' }];
  const store = renderWithQueryEditor({
    ...extraQueryEditor2,
    dbId: mockedDatabase.id,
    schema: 'main',
    sql: 'SELECT ...',
  });

  await userEvent.click(screen.getByRole('button', { name: 'Select table' }));

  await waitFor(() =>
    expect(getCurrentEditorSql(store, extraQueryEditor2.id)).toBe(
      'SELECT * FROM main.ab_user',
    ),
  );
});

test('replaces the previous autogenerated SQL when a MART is added to an existing multi-select', async () => {
  mockSelectedTables = [
    { label: 'ab_user', value: 'ab_user', type: 'table' },
    {
      label: 'Malaria Routine Monthly',
      value: 'sv_4_malaria_routine_monthly_datasets_mart',
      type: 'dataset',
    },
  ];

  const store = renderWithQueryEditor(
    {
      ...extraQueryEditor2,
      dbId: mockedDatabase.id,
      schema: 'main',
      sql: 'SELECT * FROM main.ab_user',
    },
    [
      {
        id: 'existing-table',
        dbId: mockedDatabase.id,
        catalog: null,
        schema: 'main',
        name: 'ab_user',
        queryEditorId: extraQueryEditor2.id,
        expanded: true,
        type: 'table',
      },
    ],
  );

  await userEvent.click(screen.getByRole('button', { name: 'Select table' }));

  await waitFor(() =>
    expect(getCurrentEditorSql(store, extraQueryEditor2.id)).toBe(
      'SELECT * FROM main.sv_4_malaria_routine_monthly_datasets_mart',
    ),
  );
});
